/**
 * Emitting TypeScript from an OpenAPI document: route modules, `api/schemas.ts`, and
 * `api.types.ts`.
 *
 * A hand-written string printer, not the AST factory. `Emitter.printNode` base64-encodes and
 * round-trips through the tsgo child, it is only reachable via a `Project`, and `Node.jsDoc` is
 * readonly with no way to attach a synthetic comment — and JSDoc *is* the channel that carries
 * OpenAPI metadata, so a printer that cannot write JSDoc cannot do this job.
 *
 * These files are exempt from oxfmt (see docs/CONTRIBUTING/FILE_SPECIFIC_GUIDELINES.md), so the
 * bytes this produces are final.
 */

import { STATUS_CODES } from 'node:http'
import { compareCodePoints, isMethod, sorted, type Document, type Method, type OperationObject, type ParameterObject, type Schema, type SchemaType } from '../openapi/main.ts'

const HEADER = '// Generated by @plushveil/api. Do not edit.'
const INDENT = '  '

/**
 * A file to write, as a path relative to its root plus its contents.
 */
export interface Emitted {
  path: string
  text: string
}

function isIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
}

function key(name: string): string {
  return isIdentifier(name) ? name : `'${name.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/**
 * Renders a JSDoc block. Always multi-line, always with a blank separator before the first tag, so
 * the shape is one thing rather than several.
 */
function jsdoc(description: string | undefined, tags: [string, string | undefined][], indent: string): string {
  const lines: string[] = []
  if (description) for (const line of description.split('\n')) lines.push(line.trimEnd())
  if (description && tags.length > 0) lines.push('')
  for (const [name, value] of tags) lines.push(value ? `@${name} ${value}` : `@${name}`)
  if (lines.length === 0) return ''
  // Always the multi-line form: it is what this project's formatter produces, so emitting the
  // single-line variant would mean `oxfmt --check` failed on our own output.
  return `${indent}/**\n${lines.map((l) => `${indent} *${l ? ` ${l}` : ''}`).join('\n')}\n${indent} */\n`
}

/**
 * The JSDoc tags a schema's constraints map back to.
 */
function schemaTags(schema: Schema): [string, string | undefined][] {
  const tags: [string, string | undefined][] = []
  // Typed narrowly on purpose: a stray object here would be emitted as '[object Object]'.
  const add = (name: string, value: boolean | number | string | undefined): void => {
    if (value !== undefined) tags.push([name, String(value)])
  }

  add('format', schema.format)
  add('pattern', schema.pattern)
  add('minLength', schema.minLength)
  add('maxLength', schema.maxLength)
  add('minimum', schema.minimum)
  add('maximum', schema.maximum)
  add('exclusiveMinimum', schema.exclusiveMinimum)
  add('exclusiveMaximum', schema.exclusiveMaximum)
  add('multipleOf', schema.multipleOf)
  add('minItems', schema.minItems)
  add('maxItems', schema.maxItems)
  add('minProperties', schema.minProperties)
  add('maxProperties', schema.maxProperties)
  if (schema.uniqueItems) tags.push(['uniqueItems', undefined])
  if (schema.deprecated) tags.push(['deprecated', undefined])
  if (schema.readOnly) tags.push(['readOnly', undefined])
  if (schema.writeOnly) tags.push(['writeOnly', undefined])
  if (schema.title !== undefined) tags.push(['title', schema.title])
  if (schema.default !== undefined) tags.push(['default', JSON.stringify(schema.default)])
  if (schema.example !== undefined) tags.push(['example', JSON.stringify(schema.example)])
  return tags
}

/**
 * The schema's `type` as an array, however it was written.
 */
function typeList(schema: Schema): SchemaType[] {
  if (Array.isArray(schema.type)) return schema.type
  return schema.type === undefined ? [] : [schema.type]
}

/**
 * Renders a schema as a TypeScript type expression.
 */
export function typeOf(schema: Schema, indent: string): string {
  if (schema.$ref) {
    const name = schema.$ref.split('/').pop()
    if (!name) throw new Error(`Cannot name a type for the reference ${schema.$ref}`)
    return name
  }

  if (schema.const !== undefined) return JSON.stringify(schema.const)

  if (schema.enum && schema.enum.length > 0) {
    return schema.enum.map((value) => (typeof value === 'string' ? quote(value) : JSON.stringify(value))).join(' | ')
  }

  if (schema.oneOf) return schema.oneOf.map((s) => typeOf(s, indent)).join(' | ')
  if (schema.anyOf) return schema.anyOf.map((s) => typeOf(s, indent)).join(' | ')
  if (schema.allOf) return schema.allOf.map((s) => typeOf(s, indent)).join(' & ')

  const types = typeList(schema)
  if (types.length > 1) return types.map((t) => typeOf({ ...schema, type: t }, indent)).join(' | ')

  switch (types[0]) {
    case 'string':
      return schema.format === 'binary' ? 'Uint8Array' : 'string'
    case 'number':
      return 'number'
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'null':
      return 'null'
    case 'array': {
      if (schema.prefixItems) return `[${schema.prefixItems.map((s) => typeOf(s, indent)).join(', ')}]`
      const item = typeof schema.items === 'object' ? typeOf(schema.items, indent) : 'unknown'
      return item.includes(' ') ? `Array<${item}>` : `${item}[]`
    }
    case 'object':
      return objectType(schema, indent)
    default:
      return schema.properties ? objectType(schema, indent) : 'unknown'
  }
}

function objectType(schema: Schema, indent: string): string {
  const properties = schema.properties ?? {}
  const names = sorted(Object.keys(properties), compareCodePoints)
  const required = new Set(schema.required ?? [])
  const inner = `${indent}${INDENT}`

  const members: string[] = []
  for (const name of names) {
    const property = properties[name]
    const doc = jsdoc(property.description, schemaTags(property), inner)
    members.push(`${doc}${inner}${key(name)}${required.has(name) ? '' : '?'}: ${typeOf(property, inner)}`)
  }

  if (typeof schema.additionalProperties === 'object') {
    members.push(`${inner}[key: string]: ${typeOf(schema.additionalProperties, inner)}`)
  }

  if (members.length === 0) return schema.additionalProperties === false ? 'Record<string, never>' : 'Record<string, unknown>'
  return `{\n${members.join('\n')}\n${indent}}`
}

/**
 * Emits `api/schemas.ts` from `components/schemas`.
 */
export function emitSchemas(document: Document): string {
  const schemas = document.components?.schemas ?? {}
  const names = sorted(Object.keys(schemas), compareCodePoints)
  if (names.length === 0) return `${HEADER}\n`

  const blocks = names.map((name) => {
    const schema = schemas[name]
    const doc = jsdoc(schema.description, [], '')
    // An object shape becomes an interface; anything else has to be an alias.
    const body = typeOf({ ...schema, description: undefined }, '')
    if (body.startsWith('{')) return `${doc}export interface ${name} ${body}`
    return `${doc}export type ${name} = ${body}`
  })

  return `${HEADER}\n\n${blocks.join('\n\n')}\n`
}

/**
 * The tags that belong on an operation's JSDoc.
 */
function operationTags(operation: OperationObject): [string, string | undefined][] {
  const tags: [string, string | undefined][] = []
  if (operation.operationId) tags.push(['operationId', operation.operationId])
  if (operation.tags && operation.tags.length > 0) tags.push(['tags', operation.tags.join(' ')])
  if (operation.deprecated) tags.push(['deprecated', undefined])
  for (const requirement of operation.security ?? []) {
    for (const [name, scopes] of Object.entries(requirement)) tags.push(['security', [name, ...scopes].join(' ')])
  }
  return tags
}

const BAG_FOR: Record<string, string> = { path: 'path', query: 'query', header: 'headers', cookie: 'cookies' }

/**
 * Renders the `Operation` interface body shared by a route module and `api.types.ts`.
 */
function operationBody(operation: OperationObject, indent: string): string {
  const inner = `${indent}${INDENT}`
  const parts: string[] = []

  const bags = new Map<string, ParameterObject[]>()
  for (const parameter of operation.parameters ?? []) {
    const bag = BAG_FOR[parameter.in]
    if (!bag) continue
    const list = bags.get(bag) ?? []
    list.push(parameter)
    bags.set(bag, list)
  }

  for (const bag of ['path', 'query', 'headers', 'cookies']) {
    const parameters = bags.get(bag)
    if (!parameters) continue
    const members = sorted(parameters, (a, b) => compareCodePoints(a.name, b.name)).map((parameter) => {
      const schema = parameter.schema ?? {}
      const doc = jsdoc(parameter.description, schemaTags(schema), `${inner}${INDENT}`)
      const optional = parameter.in === 'path' || parameter.required ? '' : '?'
      return `${doc}${inner}${INDENT}${key(parameter.name)}${optional}: ${typeOf(schema, `${inner}${INDENT}`)}`
    })
    parts.push(`${inner}${bag}: {\n${members.join('\n')}\n${inner}}`)
  }

  const bodySchema = operation.requestBody?.content?.['application/json']?.schema
  // Emitted only when there is one. An absent key is how the client tells "no request body" from
  // "a body typed never" — `Op['body']` on a missing key resolves to `unknown`, not `never`.
  if (bodySchema) parts.push(`${inner}body${operation.requestBody?.required ? '' : '?'}: ${typeOf(bodySchema, inner)}`)

  const statuses = sorted(Object.keys(operation.responses ?? {}), (a, b) => Number(a) - Number(b))
  const responses = statuses.map((status) => {
    const response = operation.responses[status]
    const schema = response.content?.['application/json']?.schema
    const reason = STATUS_CODES[status]
    // Do not write back a description that is just the standard reason phrase, or every round trip
    // would add one.
    const description = response.description && response.description !== reason ? response.description : undefined
    // Emitted as prose rather than an `@description` tag: the formatter rewrites that tag into
    // prose anyway, and the extractor reads either form, so prose is the stable choice.
    const doc = jsdoc(description, [], `${inner}${INDENT}`)
    return `${doc}${inner}${INDENT}${status}: ${schema ? typeOf(schema, `${inner}${INDENT}`) : 'never'}`
  })
  parts.push(`${inner}responses: {\n${responses.join('\n')}\n${inner}}`)

  return `{\n${parts.join('\n')}\n${indent}}`
}

/**
 * How far a route module sits below the `api/` root. `/health` → `api/health/get.ts`, so one
 * `../` reaches `api/` and therefore `api/schemas.ts`.
 */
function depthOf(path: string): number {
  return path.split('/').filter((s) => s.length > 0).length
}

export interface EmitRouteOptions {
  /**
   * `throw` is the only mode this build implements.
   */
  handlers?: 'keep' | 'stub' | 'throw'
  /**
   * Existing text, for `--handlers keep`.
   */
  existing?: string
}

/**
 * Raised for a `--handlers` mode this build does not implement.
 */
export class UnsupportedHandlerModeError extends Error {
  readonly mode: string

  constructor(mode: string) {
    super(`The handler mode ${JSON.stringify(mode)} is not implemented in this build`)
    this.name = 'UnsupportedHandlerModeError'
    this.mode = mode
  }
}

/**
 * Emits one route module.
 */
export function emitRoute(path: string, method: Method, operation: OperationObject, options: EmitRouteOptions = {}): string {
  // Enforced here as well as in the CLI. `keep` in particular rewrites a file that already holds
  // someone's implementation, so a caller that reaches this with an unimplemented mode must fail
  // loudly rather than silently receive a `throw` stub and overwrite real work with it.
  const handlers = options.handlers ?? 'throw'
  if (handlers !== 'throw') throw new UnsupportedHandlerModeError(handlers)

  // `../` per path segment reaches the `api/` root, where schemas.ts lives.
  const up = '../'.repeat(depthOf(path))
  const referenced = collectRefs(operation)

  // The package specifier, not a relative path into src/: this is what a consumer writes, and Node
  // resolves a package's own name from inside it via the `exports` map.
  const imports: string[] = [`import { HttpError, type Handler } from '@plushveil/api/server'`]
  if (referenced.length > 0) imports.push(`import type { ${referenced.join(', ')} } from '${up}schemas.ts'`)

  const doc = jsdoc(operation.summary ?? operation.description, operationTags(operation), '')
  const body = operationBody(operation, '')

  const handler = ['export const handler: Handler<Operation> = async () => {', `${INDENT}throw new HttpError(501, { code: 'not_implemented', message: '${method.toUpperCase()} ${path} is not implemented.' })`, '}'].join(
    '\n',
  )

  return [imports.join('\n'), '', `${doc}export interface Operation ${body}`, '', handler, ''].join('\n')
}

/**
 * Every component name an operation references, sorted and deduplicated.
 */
function collectRefs(value: unknown, into = new Set<string>()): string[] {
  if (Array.isArray(value)) {
    for (const item of value) collectRefs(item, into)
  } else if (typeof value === 'object' && value !== null) {
    for (const [k, v] of Object.entries(value)) {
      if (k === '$ref' && typeof v === 'string') {
        const name = v.split('/').pop()
        if (name) into.add(name)
        continue
      }
      collectRefs(v, into)
    }
  }
  return sorted(into, compareCodePoints)
}

/**
 * Emits `api.types.ts`: the shared schemas plus the `Api` interface.
 */
export function emitApiTypes(document: Document): string {
  const schemas = document.components?.schemas ?? {}
  const names = sorted(Object.keys(schemas), compareCodePoints)

  const blocks = names.map((name) => {
    const schema = schemas[name]
    const doc = jsdoc(schema.description, [], '')
    const body = typeOf({ ...schema, description: undefined }, '')
    if (body.startsWith('{')) return `${doc}export interface ${name} ${body}`
    return `${doc}export type ${name} = ${body}`
  })

  const paths = sorted(Object.keys(document.paths ?? {}), compareCodePoints)
  const entries = paths.map((path) => {
    const item = document.paths[path]
    const methods = Object.keys(item)
      .filter(isMethod)
      .sort((a, b) => compareCodePoints(a, b))
    const operations = methods.flatMap((method) => {
      const operation = item[method]
      if (!operation) return []
      const doc = jsdoc(operation.summary ?? operation.description, operationTags(operation), `${INDENT}${INDENT}`)
      return [`${doc}${INDENT}${INDENT}${method}: ${operationBody(operation, `${INDENT}${INDENT}`)}`]
    })
    return `${INDENT}${key(path)}: {\n${operations.join('\n')}\n${INDENT}}`
  })

  const api = `export interface Api {\n${entries.join('\n')}\n}`
  return [HEADER, '', ...(blocks.length > 0 ? [blocks.join('\n\n'), ''] : []), api, ''].join('\n')
}

/**
 * Maps a spec path and method onto the route file that carries it.
 */
export function routeFileFor(path: string, method: string): string {
  const segments = path
    .split('/')
    .filter((s) => s.length > 0)
    .map((segment) => {
      if (!segment.startsWith('{') || !segment.endsWith('}')) return segment
      return `[${segment.slice(1, -1)}]`
    })
  return [...segments, `${method}.ts`].join('/')
}

/**
 * Emits every file for a document.
 */
export function emitAll(document: Document, options: EmitRouteOptions = {}): Emitted[] {
  const files: Emitted[] = []
  const paths = sorted(Object.keys(document.paths ?? {}), compareCodePoints)

  for (const path of paths) {
    const item = document.paths[path]
    for (const method of Object.keys(item).filter(isMethod)) {
      const operation = item[method]
      if (!operation) continue
      files.push({ path: routeFileFor(path, method), text: emitRoute(path, method, operation, options) })
    }
  }

  if (Object.keys(document.components?.schemas ?? {}).length > 0) {
    files.push({ path: 'schemas.ts', text: emitSchemas(document) })
  }

  return files
}
