// Generated by @plushveil/api. Do not edit.

/**
 * Service health, as reported by `get /health`.
 */
export interface HealthStatus {
  /**
   * Whether every downstream dependency answered.
   */
  dependenciesReady: boolean
  /**
   * Set only when the caller asked for detail.
   */
  region?: string
  status: 'degraded' | 'down' | 'ok'
  /**
   * Seconds since the process started.
   */
  uptime: number
}

export interface Api {
  '/health': {
    /**
     * Report service health.
     *
     * @operationId getHealth
     * @tags ops
     */
    get: {
      query: {
        /**
         * Include the region in the response.
         */
        verbose?: boolean
      }
      responses: {
        200: HealthStatus
      }
    }
  }
}
