// Generated by @plushveil/api. Do not edit.

import type { Content } from '@plushveil/api/server'

export interface Api {
  '/export': {
    /**
     * Export a report, as a PDF or a CSV depending on `format`.
     *
     * @operationId exportReport
     */
    get: {
      query: {
        format: 'csv' | 'pdf'
      }
      responses: {
        /**
         * Report
         */
        200: Content<'application/pdf', Uint8Array> | Content<'text/csv', string>
        404: never
      }
    }
  }
  '/upload': {
    /**
     * Upload a file's bytes.
     *
     * @operationId uploadFile
     */
    put: {
      body: Content<'application/octet-stream', ReadableStream<Uint8Array>>
      responses: {
        /**
         * Accepted
         */
        204: never
      }
    }
  }
}
